# Generated by Django 2.2.4 on 2019-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stuinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
