# Generated by Django 2.2.4 on 2019-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190925_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
