# Generated by Django 2.2.4 on 2019-09-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190926_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userInfo', to_field='username'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=255, unique='True'),
        ),
    ]
