# Generated by Django 2.2.4 on 2019-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190926_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
