# Generated by Django 2.2.4 on 2019-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190926_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='caste',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='nationality',
            field=models.CharField(default=124124, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
