# Generated by Django 2.2.4 on 2019-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191028_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='age',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
