# Generated by Django 2.2.4 on 2019-10-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stuinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
