# Generated by Django 2.2.4 on 2019-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191028_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='address',
            field=models.CharField(default=11212, max_length=255),
            preserve_default=False,
        ),
    ]
