# Generated by Django 2.2.4 on 2019-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
