# Generated by Django 2.2.4 on 2019-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_feed_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
