# Generated by Django 2.2.4 on 2019-11-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191117_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='dept',
            field=models.CharField(default=122324, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='sem',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
