# Generated by Django 2.2.4 on 2019-11-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191120_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='roll',
            field=models.CharField(default=12, max_length=5),
            preserve_default=False,
        ),
    ]
